name: HertzVST
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.6.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - attrs==25.3.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.0
      - bleach==6.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - decorator==5.2.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - diffusers==0.35.1
      - docopt==0.6.2
      - einops==0.8.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - fonttools==4.60.0
      - fsspec==2025.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.1
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.4
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.9
      - loguru==0.7.3
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mistune==3.1.4
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.3
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - packaging==25.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.3.0
      - pipreqs==0.5.0
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - protobuf==6.32.1
      - psutil==7.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.36.2
      - regex==2025.9.18
      - requests==2.32.5
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - sentencepiece==0.2.1
      - six==1.17.0
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.13.1
      - tinycss2==1.4.0
      - tokenizers==0.21.4
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.48.1
      - triton==3.1.0
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - yarg==0.1.9
      - zipp==3.23.0
